version: '3.10'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    environment:
      SA_PASSWORD: "Fr@0ules123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql

  api:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mssql+pytds://sa:Fr@0ules123!@db:1433/db?driver=ODBC+Driver+17+for+SQL+Server

  mock_rest_broker:
    build:
      context: .
      dockerfile: Dockerfile.mockbroker
    ports:
      - "9000:9000"
    command: uvicorn mock_rest_broker:app --host 0.0.0.0 --port 9000 --reload

volumes:
  mssqldata:
