version: '3.10'
services:
  mssql_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    environment:
      SA_PASSWORD: "Fr@0ules123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
          - mssql_data:/var/opt/mssql

  api:
    build: .
    depends_on:
      - mssql_db
    ports:
      - "8000:8000"
    environment:
      - DB_SERVER=db
      - DB_USER=sa
      - DB_PASSWORD=Fr@0ules123!
      - DB_NAME=master

  mock_rest_broker:
    build:
      context: .
      dockerfile: Dockerfile.mockbroker
    ports:
      - "9000:9000"
    command: uvicorn mock_rest_broker:app --host 0.0.0.0 --port 9000 --reload

volumes:
   mssql_data: