name: trading
channels:
  - conda-forge
dependencies:
  - python=3.10
  - fastapi
  - uvicorn
  - pydantic
  - httpx
  - passlib
  - pip
  - pip:
      - python-jose[cryptography]
      - pycryptodome
      - sqlalchemy
      - pyodbc
